id: IB2C2FA87
ocr_import_info:
  timestamp: '2023-06-05T09:21:46.149583+00:00'
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.8
  sponsor: DS
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-05 10:49:47.230438+00:00
last_modified: 2023-06-05 10:49:47.230446+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W8684
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8684
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤཱཀྱ་རིན་ཆེན།
  languages:
  - bo
  author: འབྲུག་རྗེ་མཁན་པོ ༠༩་ཤཱཀྱ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9483361124411316
  ocr_word_median_confidence_index: 0.99212983
bases:
  I4371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4371
      total_pages: 660
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4371.txt
    statistics:
      ocr_word_median_confidence_index: 0.9935937
      ocr_word_mean_confidence_index: 0.9513961246404623
  I4365:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4365
      total_pages: 612
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4365.txt
    statistics:
      ocr_word_median_confidence_index: 0.9694883
      ocr_word_mean_confidence_index: 0.9157178123245538
  I4369:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4369
      total_pages: 590
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4369.txt
    statistics:
      ocr_word_median_confidence_index: 0.9979900749999999
      ocr_word_mean_confidence_index: 0.9654725293544175
  I4366:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4366
      total_pages: 836
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4366.txt
    statistics:
      ocr_word_median_confidence_index: 0.9918181
      ocr_word_mean_confidence_index: 0.9478332712940353
  I4372:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4372
      total_pages: 514
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4372.txt
    statistics:
      ocr_word_median_confidence_index: 0.9974087
      ocr_word_mean_confidence_index: 0.9595371203348853
  I4367:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4367
      total_pages: 654
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4367.txt
    statistics:
      ocr_word_median_confidence_index: 0.991263985
      ocr_word_mean_confidence_index: 0.950126025433444
  I4370:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4370
      total_pages: 544
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4370.txt
    statistics:
      ocr_word_median_confidence_index: 0.98806682
      ocr_word_mean_confidence_index: 0.9441440190587006
  I4368:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4368
      total_pages: 478
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4368.txt
    statistics:
      ocr_word_median_confidence_index: 0.98666495
      ocr_word_mean_confidence_index: 0.9437701341505904
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
